---
galaxy_info:
  role_name: install_opt
  namespace: jfx
  author: FX Soubirou
  description: Ansible role that downloads and installs a product in /opt directory.

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - common
    - debian
    - installation
    - opt
    - ubuntu


dependencies: []
