---
- name: Test nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true
    enabled: true
